pipeline {
  agent any

  stages {
    stage('Clone Repo') {
      steps {
        git 'https://github.com/mohanbabureddy/Rentapp.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }

    stage('Dockerize') {
      steps {
        sh 'docker build -t rentapp-frontend .'
      }
    }

    stage('Deploy (optional)') {
      steps {
        echo "Deploy the container using docker run or push to a registry"
      }
    }
  }
}
